server:
  port: ${SERVER_PORT}
spring:
  application:
    name: mocktalkback
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app:
  oauth2:
    code-ttl-seconds: ${OAUTH2_CODE_TTL_SECONDS:60}
    redirect-path: ${OAUTH2_REDIRECT_PATH:/oauth/callback}
    remember-me-default: ${OAUTH2_REMEMBER_ME_DEFAULT:false}
