global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "mocktalkback"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8083"]

  - job_name: "dynamic-apps"
    metrics_path: "/actuator/prometheus"
    file_sd_configs:
      - files:
          # - /etc/prometheus/targets/*.json
          - /etc/prometheus/targets/dynamic-apps.json
        refresh_interval: 10s
